// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXK4G4pMjAuvqf6ty-lkYDchDCTIDHcDg',
    appId: '1:969297976891:web:c5dd62b1dbc6128eacc61e',
    messagingSenderId: '969297976891',
    projectId: 'pfinanciero-40ed1',
    authDomain: 'pfinanciero-40ed1.firebaseapp.com',
    storageBucket: 'pfinanciero-40ed1.firebasestorage.app',
    measurementId: 'G-R6SH7H63RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpC1CkEYMxFTI9X1deex0_iU-vJ95WtPA',
    appId: '1:969297976891:android:8d043a0bcf4b6b7dacc61e',
    messagingSenderId: '969297976891',
    projectId: 'pfinanciero-40ed1',
    storageBucket: 'pfinanciero-40ed1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq-wHqPuxJ6O1v0uF2S8JG6aA6quQ6CHQ',
    appId: '1:969297976891:ios:f92826df54b7fa86acc61e',
    messagingSenderId: '969297976891',
    projectId: 'pfinanciero-40ed1',
    storageBucket: 'pfinanciero-40ed1.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinanciero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq-wHqPuxJ6O1v0uF2S8JG6aA6quQ6CHQ',
    appId: '1:969297976891:ios:f92826df54b7fa86acc61e',
    messagingSenderId: '969297976891',
    projectId: 'pfinanciero-40ed1',
    storageBucket: 'pfinanciero-40ed1.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinanciero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXK4G4pMjAuvqf6ty-lkYDchDCTIDHcDg',
    appId: '1:969297976891:web:d2fd2ee70905205facc61e',
    messagingSenderId: '969297976891',
    projectId: 'pfinanciero-40ed1',
    authDomain: 'pfinanciero-40ed1.firebaseapp.com',
    storageBucket: 'pfinanciero-40ed1.firebasestorage.app',
    measurementId: 'G-QXWMJZ0WGG',
  );
}